# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_ARCHIVE_TYPE "gnutar")
SET(CPACK_DEBIAN_PACKAGE_CONFLICTS "hip-thrust, thrust")
SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/workspace/rocThrust/hipclang/build/release/debian/postinst;/workspace/rocThrust/hipclang/build/release/debian/prerm")
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "rocm-dev (>= 2.5.27), rocprim (>= 2.5)")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "rocthrust-maintainer@amd.com")
SET(CPACK_DEBIAN_PACKAGE_SECTION "devel")
SET(CPACK_GENERATOR "TGZ;ZIP;DEB")
SET(CPACK_INSTALL_CMAKE_PROJECTS "/workspace/rocThrust/hipclang/build/release;rocthrust;ALL;/")
SET(CPACK_INSTALL_PREFIX "/opt/rocm")
SET(CPACK_MODULE_PATH "/workspace/rocThrust/hipclang/cmake;/cmake;/opt/rocm/hip/cmake;/opt/rocm/share/rocm/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "rocthrust 2.10.0.455-7b420a5")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MODIFY_PATH "ON")
SET(CPACK_NSIS_PACKAGE_NAME "rocthrust")
SET(CPACK_OUTPUT_CONFIG_FILE "/workspace/rocThrust/hipclang/build/release/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Radeon Open Compute Thrust library")
SET(CPACK_PACKAGE_FILE_NAME "rocthrust-2.10.0.455-7b420a5-ubuntu-16.04_amd64")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "rocthrust 2.10.0.455-7b420a5")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "rocthrust 2.10.0.455-7b420a5")
SET(CPACK_PACKAGE_NAME "rocthrust")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Advanced Micro Devices, Inc")
SET(CPACK_PACKAGE_VERSION "2.10.0.455-7b420a5")
SET(CPACK_PACKAGE_VERSION_MAJOR "2")
SET(CPACK_PACKAGE_VERSION_MINOR "10")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_PACKAGING_INSTALL_PREFIX "/opt/rocm")
SET(CPACK_RESOURCE_FILE_LICENSE "/workspace/rocThrust/hipclang/LICENSE")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.5/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.5/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX};${CPACK_PACKAGING_INSTALL_PREFIX}/include")
SET(CPACK_RPM_PACKAGE_AUTOREQPROV "Off")
SET(CPACK_RPM_PACKAGE_CONFLICTS "hip-thrust, thrust")
SET(CPACK_RPM_PACKAGE_RELOCATABLE "Off")
SET(CPACK_RPM_PACKAGE_REQUIRES "rocm-dev >= 2.5.27, rocprim >= 2.5")
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/workspace/rocThrust/hipclang/build/release/debian/postinst")
SET(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "/workspace/rocThrust/hipclang/build/release/debian/prerm")
SET(CPACK_SET_DESTDIR "ON")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/workspace/rocThrust/hipclang/build/release/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_SYSTEM_NAME "ubuntu-16.04_amd64")
SET(CPACK_TOPLEVEL_TAG "ubuntu-16.04_amd64")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/workspace/rocThrust/hipclang/build/release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
